# Generated by Django 5.2.15 on 2026-08-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentfile',
            options={'ordering': ['-version']},
        ),
        migrations.AddField(
            model_name='documentfile',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
